config/routes.rb
Rails.application.routes.draw do
  resources :stripclubs do
    resources :reviews, only: [:create]
  end

  get 'instructions', to: 'pages#home'
  root to: 'stripclubs#index'

  get "/reviews", to: "reviews#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :stripclub

  validates :content, presence: true
  validates :rating, inclusion: {in: [0,1,2,3], allow_nil: false}
end

app/models/stripclub.rb
class Stripclub < ApplicationRecord
  has_many :reviews

  validates :name, :location, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def create
    @review = Review.new(review_params)

    @review.stripclub = Stripclub.find(params[:stripclub_id])

    if @review.save
      redirect_to stripclub_path(@review.stripclub)
    else
      @stripclub = @review.stripclub
      render "stripclubs/show"
    end

  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/stripclubs_controller.rb
class StripclubsController < ApplicationController
  before_action :set_stripclub, only: [:show, :edit, :update, :destroy]

  # GET /stripclubs
  # GET /stripclubs.json
  def index
    @stripclubs = Stripclub.all

    if !params[:search].nil? && !params[:search].empty?
      @stripclubs = @stripclubs.where(name: params[:search])
    end
  end

  # GET /stripclubs/1
  # GET /stripclubs/1.json
  def show
    @review = Review.new
  end

  # GET /stripclubs/new
  def new
    @stripclub = Stripclub.new
  end

  # GET /stripclubs/1/edit
  def edit
  end

  # POST /stripclubs
  # POST /stripclubs.json
  def create
    @stripclub = Stripclub.new(stripclub_params)

    respond_to do |format|
      if @stripclub.save
        format.html { redirect_to @stripclub, notice: 'Stripclub was successfully created.' }
        format.json { render :show, status: :created, location: @stripclub }
      else
        format.html { render :new }
        format.json { render json: @stripclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stripclubs/1
  # PATCH/PUT /stripclubs/1.json
  def update
    respond_to do |format|
      if @stripclub.update(stripclub_params)
        format.html { redirect_to @stripclub, notice: 'Stripclub was successfully updated.' }
        format.json { render :show, status: :ok, location: @stripclub }
      else
        format.html { render :edit }
        format.json { render json: @stripclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stripclubs/1
  # DELETE /stripclubs/1.json
  def destroy
    @stripclub.destroy
    respond_to do |format|
      format.html { redirect_to stripclubs_url, notice: 'Stripclub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stripclub
      @stripclub = Stripclub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stripclub_params
      params.require(:stripclub).permit(:name, :location, :female_dancers, :male_dancers, :phone_number, :music)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stripclubs_helper.rb
module StripclubsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Livecode StripClub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container main">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Livecode!</h1>

<h2>1. Stripclub CRUD</h2>
<ul>
  <li>Scaffold Stripclub.</li>
  <li>Change root_path to index of Stripclubs.</li>
  <li>Add class table and table-striped to index table.</li>
  <li>Add some validations on the model Stripclub.</li>
  <li>Seed your database with 3 Stripclubs.</li>
  <li>Link the 'New Stripclub Button' to new page.</li>
  <li>Implement a search action on the navbar.</li>
</ul>

<h2>2. Reviews</h2>
<ul>
  <li>Create a model Review.</li>
  <li>Where do you insert the review form?</li>
  <li>How do you define your route to create a review?</li>
  <li>Create the ReviewsController and add a method create.</li>
  <li>Where do you display reviews?</li>
  <li>Link the notification envelope to a list of all reviews.</li>
  <li>Show the total number of reviews on the notification envelope</li>
</ul>

<h2>3. Go Crazy</h2>

app/views/reviews/_form.html.erb
<%= simple_form_for [@stripclub, @review] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :rating, collection: [0,1,2,3] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Stripclub</th>
      <th class="text-right">Rating</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.stripclub.name %></td>
        <td class="text-right"><%= review.rating %></td>
        <td><%= review.content %></td>
        <td><%= link_to 'Show', review.stripclub %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/shared/_footer.html.erb
<div id="footer">
  Developed by the best students ever!
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="/" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something" name="search">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "/reviews", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue"><%= Review.all.count %></div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "me.jpeg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "New Stripclub"), new_stripclub_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/stripclubs/_form.html.erb
<%= simple_form_for(@stripclub) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :female_dancers %>
    <%= f.input :male_dancers %>
    <%= f.input :phone_number %>
    <%= f.input :music %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stripclubs/edit.html.erb
<h1>Editing Stripclub</h1>

<%= render 'form', stripclub: @stripclub %>

<%= link_to 'Show', @stripclub %> |
<%= link_to 'Back', stripclubs_path %>

app/views/stripclubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stripclubs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Female dancers</th>
      <th>Male dancers</th>
      <th>Phone number</th>
      <th>Music</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stripclubs.each do |stripclub| %>
      <tr>
        <td><%= stripclub.name %></td>
        <td><%= stripclub.location %></td>
        <td><%= stripclub.female_dancers %></td>
        <td><%= stripclub.male_dancers %></td>
        <td><%= stripclub.phone_number %></td>
        <td><%= stripclub.music %></td>
        <td><%= link_to 'Show', stripclub %></td>
        <td><%= link_to 'Edit', edit_stripclub_path(stripclub) %></td>
        <td><%= link_to 'Destroy', stripclub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stripclub', new_stripclub_path %>

app/views/stripclubs/new.html.erb
<h1>New Stripclub</h1>

<%= render 'form', stripclub: @stripclub %>

<%= link_to 'Back', stripclubs_path %>

app/views/stripclubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stripclub.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @stripclub.location %>
</p>

<p>
  <strong>Female dancers:</strong>
  <%= @stripclub.female_dancers %>
</p>

<p>
  <strong>Male dancers:</strong>
  <%= @stripclub.male_dancers %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @stripclub.phone_number %>
</p>

<p>
  <strong>Music:</strong>
  <%= @stripclub.music %>
</p>

<%= link_to 'Edit', edit_stripclub_path(@stripclub) %> |
<%= link_to 'Back', stripclubs_path %>

<%= render "reviews/form" %>

<ul>
<% @stripclub.reviews.each do |review| %>
  <li> <%= review.rating %> - <%= review.content%></li>
<%end%>
</ul>